'use strict';function v(k,h,e,g){k.f.aa(k.F,h,e,g,void 0)}function x(k,h,e,g){k.f.l?v(k,h,e,g):k.f.sb()._OnMessageFromDOM({type:"event",component:k.F,handler:h,dispatchOpts:g||null,data:e,responseId:null})}function y(k,h,e){k.f.a(k.F,h,e)}function H(k,h){for(const [e,g]of h)y(k,e,g)}window.Ca=class{constructor(k,h){this.f=k;this.F=h}za(){}};
window.hb=class{constructor(k,h){this.Sa=k;this.dc=h;this.A=-1;this.U=-Infinity;this.jc=()=>{this.A=-1;this.U=Date.now();this.G=!0;this.Sa();this.G=!1};this.Ta=this.G=!1}};"use strict";function I(k,h){const e=h.elementId,g=k.Ba(e,h);k.h.set(e,g);h.isVisible||(g.style.display="none");g.addEventListener("focus",()=>{J(k,"elem-focused",e)});g.addEventListener("blur",()=>{J(k,"elem-blurred",e)});k.S&&document.body.appendChild(g)}
function K(k,h,e){y(k,h,g=>{const q=k.h.get(g.elementId);return e(q,g)})}function J(k,h,e,g){g||(g={});g.elementId=e;v(k,h,g)}
window.bb=class extends self.Ca{constructor(k,h){super(k,h);this.h=new Map;this.S=!0;H(this,[["create",e=>I(this,e)],["destroy",e=>{{e=e.elementId;const g=this.h.get(e);this.S&&g.parentElement.removeChild(g);this.h.delete(e)}}],["set-visible",e=>{this.S&&(this.h.get(e.elementId).style.display=e.isVisible?"":"none")}],["update-position",e=>{if(this.S){var g=this.h.get(e.elementId);g.style.left=e.left+"px";g.style.top=e.top+"px";g.style.width=e.width+"px";g.style.height=e.height+"px";e=e.fontSize;null!==
e&&(g.style.fontSize=e+"em")}}],["update-state",e=>{{const g=this.h.get(e.elementId);this.ca(g,e)}}],["focus",e=>{{const g=this.h.get(e.elementId);e.focus?g.focus():g.blur()}}],["set-css-style",e=>{this.h.get(e.elementId).style[e.prop]=e.val}],["set-attribute",e=>{this.h.get(e.elementId).setAttribute(e.name,e.val)}],["remove-attribute",e=>{this.h.get(e.elementId).removeAttribute(e.name)}]]);K(this,"get-element",e=>e)}Ba(){throw Error("required override");}ca(){throw Error("required override");}};
"use strict";
{const k=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);function h(b,a){const c=document.createElement("script");c.async=!1;"module"===a&&(c.type="module");if(b.nc)c.textContent=b.qc,document.head.appendChild(c);else return new Promise((d,f)=>{c.onload=d;c.onerror=f;c.src=b;document.head.appendChild(c)})}let e=!1,g=!1;function q(){if(!e){try{new Worker("blob://",{get type(){g=!0}})}catch(b){}e=!0}return g}let t=new Audio;const m={"audio/webm; codecs=opus":!!t.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!t.canPlayType("audio/ogg; codecs=opus"),
"audio/webm; codecs=vorbis":!!t.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!t.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!t.canPlayType("audio/mp4"),"audio/mpeg":!!t.canPlayType("audio/mpeg")};t=null;async function r(b){b=await z(b);return(new TextDecoder("utf-8")).decode(b)}function z(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=f=>a(f.target.result);d.onerror=f=>c(f);d.readAsArrayBuffer(b)})}const D=[];let B=0;window.RealFile=window.File;const A=
[],E=new Map,u=new Map;let F=0;const C=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");C.push(b)};const G=new Set(["cordova","playable-ad","instant-games"]);window.ba=class b{constructor(a){this.l=a.sc;this.I=null;this.b="";this.X=a.pc;this.i=a.$a;this.L={};this.sa=this.Xa=null;this.T=[];this.H=this.g=this.va=null;this.u=-1;this.ic=()=>this.Pb();this.Wa=[];this.c=a.Ya;!this.l||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&
("module"!==this.i||q())||(this.l=!1);G.has(this.c)&&this.l&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this.l=!1);this.V=this.j=null;"html5"!==this.c&&"playable-ad"!==this.c||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.a("runtime","cordova-fetch-local-file",
c=>this.Bb(c));this.a("runtime","create-job-worker",()=>this.Cb());"cordova"===this.c?document.addEventListener("deviceready",()=>this.Ha(a)):this.Ha(a)}Da(){return k&&"cordova"===this.c}N(){return k&&G.has(this.c)||navigator.standalone}async Ha(a){if("playable-ad"===this.c){this.j=self.c3_base64files;this.V={};await this.nb();for(let d=0,f=a.B.length;d<f;++d){var c=a.B[d].toLowerCase();this.V.hasOwnProperty(c)?a.B[d]={nc:!0,qc:this.V[c]}:this.j.hasOwnProperty(c)&&(a.B[d]=URL.createObjectURL(this.j[c]))}}a.kc?
this.b=a.kc:(c=location.origin,this.b=("null"===c?"file:///":c)+location.pathname,c=this.b.lastIndexOf("/"),-1!==c&&(this.b=this.b.substr(0,c+1)));a.uc&&(this.L=a.uc);c=new MessageChannel;this.I=c.port1;this.I.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Mb(d));this.H=new self.fb(this);await L(this.H);this.Ea();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();
this.l?await this.ub(a,c.port2):await this.tb(a,c.port2)}ga(a){a=this.L.hasOwnProperty(a)?this.L[a]:a.endsWith("/workermain.js")&&this.L.hasOwnProperty("workermain.js")?this.L["workermain.js"]:"playable-ad"===this.c&&this.j.hasOwnProperty(a.toLowerCase())?this.j[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async Z(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if(this.Da()&&"file:"===location.protocol)return a=await this.Y(this.X+a),new Worker(URL.createObjectURL(new Blob([a],
{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}o(){return Math.max(window.innerWidth,1)}m(){return Math.max(window.innerHeight,1)}Ea(){if(this.N()){const a=document.documentElement.style,c=document.body.style,d=window.innerWidth<window.innerHeight,f=d?window.screen.width:window.screen.height;c.height=a.height=
(d?window.screen.height:window.screen.width)+"px";c.width=a.width=f+"px"}}Ga(a){var c=this.H;return{baseUrl:this.b,windowInnerWidth:this.o(),windowInnerHeight:this.m(),devicePixelRatio:window.devicePixelRatio,isFullscreen:b.$(),projectData:a.zc,scriptsType:a.$a,previewImageBlobs:window.cr_previewImageBlobs||this.j,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileUrls:window.cr_previewProjectFiles,swClientId:window.xc||"",exportType:a.Ya,isDebug:-1<self.location.search.indexOf("debug"),
ife:!!self.yc,jobScheduler:{inputPort:c.qa,outputPort:c.ua,maxNumWorkers:c.fc},supportedAudioFormats:m,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.X+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.X+"opus.wasm.wasm",isiOSCordova:this.Da(),isiOSWebView:this.N(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async ub(a,c){var d=this.ga(a.tc);this.Xa=await this.Z(d,this.b,{type:this.i,name:"Runtime"});this.g=document.createElement("canvas");this.g.style.display=
"none";d=this.g.transferControlToOffscreen();document.body.appendChild(this.g);window.c3canvas=this.g;this.Xa.postMessage(Object.assign(this.Ga(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:d,workerDependencyScripts:a.xa||[],engineScripts:a.B,projectScripts:a.M,mainProjectScript:a.Za,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,d,...M(this.H)]);this.T=A.map(f=>new f(this));this.Fa();self.c3_callFunction=(f,l)=>this.va.vb(f,l);"preview"===this.c&&(self.goToLastErrorScript=()=>
this.aa("runtime","go-to-last-error-script"))}async tb(a,c){this.g=document.createElement("canvas");this.g.style.display="none";document.body.appendChild(this.g);window.c3canvas=this.g;this.T=A.map(l=>new l(this));this.Fa();var d=a.B.map(l=>"string"===typeof l?(new URL(l,this.b)).toString():l);Array.isArray(a.xa)&&d.unshift(...a.xa);d=await Promise.all(d.map(l=>this.ia(l,this.i)));await Promise.all(d.map(l=>h(l,this.i)));const f=self.C3_ProjectScriptsStatus;if("module"===this.i){d=a.Za;const l=a.M;
for(let [p,n]of l)if(n||(n=p),p===d)try{n=await this.ia(n,this.i),await h(n,this.i),"preview"!==this.c||f[p]||this.Na(p,"main script did not run to completion")}catch(w){this.Na(p,w)}else if("scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))n=await this.ia(n,this.i),await h(n,this.i)}else if(a.M&&0<a.M.length)try{if(await Promise.all(a.M.map(l=>h(l[1],this.i))),Object.values(f).some(l=>!l)){self.setTimeout(()=>this.Oa(f),100);return}}catch(l){console.error("[Preview] Error loading project scripts: ",
l);self.setTimeout(()=>this.Oa(f),100);return}"preview"===this.c&&"object"!==typeof self.vc.wc?(this.D(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Ga(a),{isInWorker:!1,messagePort:c,canvas:this.g,runOnStartupFunctions:C}),this.Ja(),this.sa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.sa,
a))}Oa(a){this.D();a=`Failed to load project script '${Object.entries(a).filter(c=>!c[1]).map(c=>c[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+a);alert(a)}Na(a,c){this.D();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ja(){this.D()}D(){const a=window.lc;a&&(a.parentElement.removeChild(a),
window.lc=null)}async Cb(){const a=await N(this.H);return{outputPort:a,transferables:[a]}}sb(){if(this.l)throw Error("not available in worker mode");return this.sa}aa(a,c,d,f,l){this.I.postMessage({type:"event",component:a,handler:c,dispatchOpts:f||null,data:d,responseId:null},l)}gb(a,c){const d=F++,f=new Promise((l,p)=>{u.set(d,{resolve:l,reject:p})});this.I.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:c,responseId:d},void 0);return f}["_OnMessageFromRuntime"](a){const c=
a.type;if("event"===c)return this.Hb(a);if("result"===c)this.Tb(a);else if("runtime-ready"===c)this.Ub();else if("alert-error"===c)this.D(),alert(a.message);else if("creating-runtime"===c)this.Ja();else throw Error(`unknown message '${c}'`);}Hb(a){const c=a.component,d=a.handler,f=a.data,l=a.responseId;if(a=E.get(c))if(a=a.get(d)){var p=null;try{p=a(f)}catch(n){console.error(`Exception in '${c}' handler '${d}':`,n);null!==l&&this.P(l,!1,""+n);return}if(null===l)return p;p&&p.then?p.then(n=>this.P(l,
!0,n)).catch(n=>{console.error(`Rejection from '${c}' handler '${d}':`,n);this.P(l,!1,""+n)}):this.P(l,!0,p)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}P(a,c,d){let f;d&&d.transferables&&(f=d.transferables);this.I.postMessage({type:"result",responseId:a,isOk:c,result:d},f)}Tb(a){const c=a.responseId,d=a.isOk;a=a.result;const f=u.get(c);d?f.resolve(a):f.reject(a);u.delete(c)}a(a,c,d){let f=E.get(a);f||(f=new Map,
E.set(a,f));if(f.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);f.set(c,d)}static ya(a){if(A.includes(a))throw Error("DOM handler already added");A.push(a)}Fa(){for(const a of this.T)if("runtime"===a.F){this.va=a;return}throw Error("cannot find runtime DOM handler");}Mb(a){this.aa("debugger","message",a)}Ub(){for(const a of this.T)a.za()}static $(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Pa(){-1===this.u&&this.Wa.length&&
(this.u=requestAnimationFrame(this.ic))}lb(){-1!==this.u&&(cancelAnimationFrame(this.u),this.u=-1)}Pb(){this.u=-1;for(const a of this.Wa)a();this.Pa()}oa(){this.va.oa()}cb(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}eb(a){return!this.cb(a)}async ia(a,c){return"cordova"===this.c&&"module"===c&&(a.startsWith("file:")||"file:"===location.protocol&&this.eb(a))?(a.startsWith(this.b)&&(a=a.substr(this.b.length)),a=await this.Y(a),URL.createObjectURL(new Blob([a],
{type:"application/javascript"}))):a}async Bb(a){const c=a.filename;switch(a.as){case "text":return await this.ab(c);case "buffer":return await this.Y(c);default:throw Error("unsupported type");}}Aa(a){const c=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((d,f)=>{window.resolveLocalFileSystemURL(c,l=>{l.file(d,f)},f)})}async ab(a){a=await this.Aa(a);return await r(a)}da(){if(D.length&&!(8<=B)){B++;var a=D.shift();this.ob(a.filename,a.rc,a.mc)}}Y(a){return new Promise((c,
d)=>{D.push({filename:a,rc:f=>{B--;this.da();c(f)},mc:f=>{B--;this.da();d(f)}});this.da()})}async ob(a,c,d){try{const f=await this.Aa(a),l=await z(f);c(l)}catch(f){d(f)}}async nb(){const a=[];for(const [c,d]of Object.entries(this.j))a.push(this.mb(c,d));await Promise.all(a)}async mb(a,c){if("object"===typeof c)this.j[a]=new Blob([c.str],{type:c.type}),this.V[a]=c.str;else{let d=await this.rb(c);d||(d=this.pb(c));this.j[a]=d}}async rb(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}pb(a){a=this.$b(a);return this.kb(a.data,a.oc)}$b(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const f=c[2];d="base64"===c[1]||"base64"===f?atob(d):decodeURIComponent(d);return{oc:a,data:d}}kb(a,c){var d=a.length;let f=d>>2,l=new Uint8Array(d),p=new Uint32Array(l.buffer,0,f),n,w;for(w=n=0;n<f;++n)p[n]=a.charCodeAt(w++)|a.charCodeAt(w++)<<8|a.charCodeAt(w++)<<16|a.charCodeAt(w++)<<24;for(d&=
3;d--;)l[w]=a.charCodeAt(w),++w;return new Blob([l],{type:c})}}}"use strict";
{const k=self.ba;function h(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const e=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),g={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},q={dispatchUserScriptEvent:!0},t={dispatchRuntimeEvent:!0};function m(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=f=>c(f);d.rel=
"stylesheet";d.href=b;document.head.appendChild(d)})}function r(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=f=>c(f);d.src=b})}async function z(b){b=URL.createObjectURL(b);try{return await r(b)}finally{URL.revokeObjectURL(b)}}function D(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=f=>a(f.target.result);d.onerror=f=>c(f);d.readAsText(b)})}async function B(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await z(b);var d=await D(b);d=(new DOMParser).parseFromString(d,
"image/svg+xml");const f=d.documentElement;if(f.hasAttribute("width")&&f.hasAttribute("height")){const l=f.getAttribute("width"),p=f.getAttribute("height");if(!l.includes("%")&&!p.includes("%"))return await z(b)}f.setAttribute("width",a+"px");f.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await z(b)}function A(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const E=new Set(["canvas",
"body","html"]);function u(b){E.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function F(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}self.C3_GetSvgImageSize=async function(b){b=await z(b);if(0<b.width&&0<b.height)return[b.width,b.height];{b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]}};self.C3_RasterSvgImageBlob=async function(b,
a,c,d,f){b=await B(b,a,c);const l=document.createElement("canvas");l.width=d;l.height=f;l.getContext("2d").drawImage(b,0,0,a,c);return l};let C=!1;document.addEventListener("pause",()=>C=!0);document.addEventListener("resume",()=>C=!1);function G(){try{return window.parent&&window.parent.document.hasFocus()}catch(b){return!1}}k.ya(class extends self.Ca{constructor(b){super(b,"runtime");this.Ua=!0;this.v=-1;this.wa="any";this.Qa=this.Ra=!1;this.ra=this.K=this.s=null;b.a("canvas","update-size",d=>this.Yb(d));
b.a("runtime","invoke-download",d=>this.Kb(d));b.a("runtime","raster-svg-image",d=>this.Qb(d));b.a("runtime","get-svg-image-size",d=>this.Ib(d));b.a("runtime","set-target-orientation",d=>this.Xb(d));b.a("runtime","register-sw",()=>this.Rb());b.a("runtime","post-to-debugger",d=>this.La(d));b.a("runtime","go-to-script",d=>this.La(d));b.a("runtime","before-start-ticking",()=>this.zb());b.a("runtime","debug-highlight",d=>this.Db(d));b.a("runtime","enable-device-orientation",()=>this.jb());b.a("runtime",
"enable-device-motion",()=>this.ib());b.a("runtime","add-stylesheet",d=>this.xb(d));b.a("runtime","alert",d=>this.yb(d));b.a("runtime","hide-cordova-splash",()=>this.Jb());const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const f=d.target;a.has(f.tagName.toLowerCase())||A(f)||d.preventDefault()});const c=b.g;window.addEventListener("selectstart",u);window.addEventListener("gesturehold",u);c.addEventListener("selectstart",u);c.addEventListener("gesturehold",
u);window.addEventListener("touchstart",u,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",u,{passive:!1}),c.addEventListener("pointerdown",u)):c.addEventListener("touchstart",u);this.J=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",F,{passive:!1});window.addEventListener("wheel",F,{passive:!1});window.addEventListener("resize",()=>this.Zb());b.N()&&window.addEventListener("focusout",()=>{{const l=
document.activeElement;if(l){var d=l.tagName.toLowerCase();var f=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?f.has(l.type.toLowerCase()||"text"):A(l)}else d=!1}d||(document.scrollingElement.scrollTop=0)});this.ta=new Set;this.hc=new WeakSet;this.ec=!1}zb(){"cordova"===this.f.c?(document.addEventListener("pause",()=>this.na(!0)),document.addEventListener("resume",()=>this.na(!1))):document.addEventListener("visibilitychange",()=>this.na(document.hidden));
return{isSuspended:!(!document.hidden&&!C)}}za(){window.addEventListener("focus",()=>this.R("window-focus"));window.addEventListener("blur",()=>{this.R("window-blur",{parentHasFocus:G()});this.J=0});window.addEventListener("fullscreenchange",()=>this.ja());window.addEventListener("webkitfullscreenchange",()=>this.ja());window.addEventListener("mozfullscreenchange",()=>this.ja());window.addEventListener("fullscreenerror",a=>this.ka(a));window.addEventListener("webkitfullscreenerror",a=>this.ka(a));
window.addEventListener("mozfullscreenerror",a=>this.ka(a));window.addEventListener("keydown",a=>this.Ka("keydown",a));window.addEventListener("keyup",a=>this.Ka("keyup",a));window.addEventListener("dblclick",a=>this.la("dblclick",a,g));window.addEventListener("wheel",a=>this.Nb(a));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{this.ha(a);this.C("pointerdown",a)}),this.f.l&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.K=new self.hb(()=>this.qb(),
5),this.K.Ta=!0,window.addEventListener("pointerrawupdate",a=>this.Ob(a))):window.addEventListener("pointermove",a=>this.C("pointermove",a)),window.addEventListener("pointerup",a=>this.C("pointerup",a)),window.addEventListener("pointercancel",a=>this.C("pointercancel",a))):(window.addEventListener("mousedown",a=>{this.ha(a);this.ma("pointerdown",a)}),window.addEventListener("mousemove",a=>this.ma("pointermove",a)),window.addEventListener("mouseup",a=>this.ma("pointerup",a)),window.addEventListener("touchstart",
a=>{this.ha(a);this.O("pointerdown",a)}),window.addEventListener("touchmove",a=>this.O("pointermove",a)),window.addEventListener("touchend",a=>this.O("pointerup",a)),window.addEventListener("touchcancel",a=>this.O("pointercancel",a)));const b=()=>this.oa();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0)}R(b,a){v(this,b,a||null,t)}o(){return this.f.o()}m(){return this.f.m()}Zb(){const b=
this.o(),a=this.m();this.R("window-resize",{innerWidth:b,innerHeight:a,devicePixelRatio:window.devicePixelRatio});this.f.N()&&(-1!==this.v&&clearTimeout(this.v),this.Ma(b,a,0))}ac(b,a,c){-1!==this.v&&clearTimeout(this.v);this.v=setTimeout(()=>this.Ma(b,a,c),48)}Ma(b,a,c){const d=this.o(),f=this.m();this.v=-1;d!=b||f!=a?this.R("window-resize",{innerWidth:d,innerHeight:f,devicePixelRatio:window.devicePixelRatio}):10>c&&this.ac(d,f,c+1)}Xb(b){this.wa=b.targetOrientation}bc(){const b=this.wa;if(screen.orientation&&
screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",a)}}ja(){const b=
k.$();b&&"any"!==this.wa&&this.bc();v(this,"fullscreenchange",{isFullscreen:b,innerWidth:this.o(),innerHeight:this.m()})}ka(b){console.warn("[Construct 3] Fullscreen request failed: ",b);v(this,"fullscreenerror",{isFullscreen:k.$(),innerWidth:this.o(),innerHeight:this.m()})}na(b){b?this.f.lb():this.f.Pa();v(this,"visibilitychange",{hidden:b})}Ka(b,a){"Backspace"===a.key&&u(a);const c=e.get(a.code)||a.code;x(this,b,{code:c,key:a.key,which:a.which,repeat:a.repeat,altKey:a.altKey,ctrlKey:a.ctrlKey,metaKey:a.metaKey,
shiftKey:a.shiftKey,timeStamp:a.timeStamp},g)}Nb(b){v(this,"wheel",{clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,deltaX:b.deltaX,deltaY:b.deltaY,deltaZ:b.deltaZ,deltaMode:b.deltaMode,timeStamp:b.timeStamp},g)}la(b,a,c){h(a)||x(this,b,{button:a.button,buttons:a.buttons,clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,timeStamp:a.timeStamp},c)}ma(b,a){if(!h(a)){var c=this.J;"pointerdown"===b&&0!==c?b="pointermove":"pointerup"===b&&0!==a.buttons&&(b="pointermove");x(this,
b,{pointerId:1,pointerType:"mouse",button:a.button,buttons:a.buttons,lastButtons:c,clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:a.timeStamp},g);this.J=a.buttons;this.la(a.type,a,q)}}C(b,a){if(this.K&&"pointermove"!==b){var c=this.K;c.G||(-1!==c.A&&(self.clearTimeout(c.A),c.A=-1),c.U=Date.now())}c=0;"mouse"===a.pointerType&&(c=this.J);x(this,b,{pointerId:a.pointerId,pointerType:a.pointerType,button:a.button,
buttons:a.buttons,lastButtons:c,clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,width:a.width||0,height:a.height||0,pressure:a.pressure||0,tangentialPressure:a.tangentialPressure||0,tiltX:a.tiltX||0,tiltY:a.tiltY||0,twist:a.twist||0,timeStamp:a.timeStamp},g);"mouse"===a.pointerType&&(c="mousemove","pointerdown"===b?c="mousedown":"pointerup"===b&&(c="mouseup"),this.la(c,a,q),this.J=a.buttons)}Ob(b){this.ra=b;b=this.K;if(-1===b.A){var a=Date.now(),c=a-b.U,d=b.dc;c>=d&&b.Ta?(b.U=a,b.G=
!0,b.Sa(),b.G=!1):b.A=self.setTimeout(b.jc,Math.max(d-c,4))}}qb(){this.C("pointermove",this.ra);this.ra=null}O(b,a){for(let c=0,d=a.changedTouches.length;c<d;++c){const f=a.changedTouches[c];x(this,b,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||
0,timeStamp:a.timeStamp},g)}}ha(b){window!==window.top&&window.focus();this.Ia(b.target)&&document.activeElement&&!this.Ia(document.activeElement)&&document.activeElement.blur()}Ia(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}jb(){this.Ra||(this.Ra=!0,window.addEventListener("deviceorientation",b=>this.Fb(b)),window.addEventListener("deviceorientationabsolute",b=>this.Gb(b)))}ib(){this.Qa||(this.Qa=!0,window.addEventListener("devicemotion",b=>this.Eb(b)))}Fb(b){v(this,
"deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},g)}Gb(b){v(this,"deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},g)}Eb(b){let a=null;var c=b.acceleration;c&&(a={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var d=b.accelerationIncludingGravity;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});
d=null;const f=b.rotationRate;f&&(d={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});v(this,"devicemotion",{acceleration:a,accelerationIncludingGravity:c,rotationRate:d,interval:b.interval,timeStamp:b.timeStamp},g)}Yb(b){const a=this.f,c=a.g;c.style.width=b.styleWidth+"px";c.style.height=b.styleHeight+"px";c.style.marginLeft=b.marginLeft+"px";c.style.marginTop=b.marginTop+"px";a.Ea();this.Ua&&(c.style.display="",this.Ua=!1)}Kb(b){const a=b.url;b=b.filename;const c=document.createElement("a"),d=
document.body;c.textContent=b;c.href=a;c.download=b;d.appendChild(c);c.click();d.removeChild(c)}async Qb(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async Ib(b){return await self.C3_GetSvgImageSize(b.blob)}async xb(b){await m(b.url)}oa(){var b=[...this.ta];this.ta.clear();if(!this.ec)for(const a of b)(b=a.play())&&b.catch(()=>
{this.hc.has(a)||this.ta.add(a)})}Jb(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Db(b){if(b.show){this.s||(this.s=document.createElement("div"),this.s.id="inspectOutline",document.body.appendChild(this.s));var a=this.s;a.style.display="";a.style.left=b.left-1+"px";a.style.top=b.top-1+"px";a.style.width=b.width+2+"px";a.style.height=b.height+2+"px";a.textContent=b.name}else this.s&&(this.s.style.display="none")}Rb(){window.C3_RegisterSW&&window.C3_RegisterSW()}La(b){window.c3_postToMessagePort&&
(b.from="runtime",window.c3_postToMessagePort(b))}vb(b,a){return this.f.gb(this.F,{name:b,params:a})}yb(b){alert(b.message)}})}"use strict";async function L(k){if(k.cc)throw Error("already initialised");k.cc=!0;var h=k.W.ga("dispatchworker.js");k.pa=await k.W.Z(h,k.b,{name:"DispatchWorker"});h=new MessageChannel;k.qa=h.port1;k.pa.postMessage({type:"_init","in-port":h.port2},[h.port2]);k.ua=await N(k)}function M(k){return[k.qa,k.ua]}
async function N(k){const h=k.Va.length;var e=k.W.ga("jobworker.js");e=await k.W.Z(e,k.b,{name:"JobWorker"+h});const g=new MessageChannel,q=new MessageChannel;k.pa.postMessage({type:"_addJobWorker",port:g.port1},[g.port1]);e.postMessage({type:"init",number:h,"dispatch-port":g.port2,"output-port":q.port2},[g.port2,q.port2]);k.Va.push(e);return q.port1}
self.fb=class{constructor(k){this.W=k;this.b=k.b;this.b="preview"===k.c?this.b+"c3/workers/":this.b+k.X;this.fc=Math.min(navigator.hardwareConcurrency||2,16);this.pa=null;this.Va=[];this.ua=this.qa=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ba({sc:!0,tc:"workermain.js",B:["scripts/c3runtime.js"],M:[],Za:"",$a:"module",pc:"scripts/",xa:[],Ya:"html5"}));"use strict";
{function k(h){h.stopPropagation()}self.ba.ya(class extends self.bb{constructor(h){super(h,"list");K(this,"set-selected-index",(e,g)=>this.Wb(e,g.selectedIndex));K(this,"add-item",(e,g)=>this.wb(e,g));K(this,"remove-item",(e,g)=>this.Sb(e,g));K(this,"set-item",(e,g)=>this.Vb(e,g));K(this,"clear",e=>this.Ab(e));K(this,"load-state",(e,g)=>this.Lb(e,g))}Ba(h,e){const g=e.isDropdown,q=e.isMultiSelect,t=e.items,m=document.createElement("select");m.style.position="absolute";m.style.userSelect="none";m.style.webkitUserSelect=
"none";m.multiple=q;g||(m.size=2);for(const r of t)m.add(this.ea(r));m.addEventListener("touchstart",k);m.addEventListener("touchmove",k);m.addEventListener("touchend",k);m.addEventListener("mousedown",k);m.addEventListener("mouseup",k);m.addEventListener("click",r=>{r.stopPropagation();(r=this.fa(m))||(r={});r.elementId=h;x(this,"click",r)});m.addEventListener("dblclick",r=>{r.stopPropagation();(r=this.fa(m))||(r={});r.elementId=h;x(this,"dblclick",r)});m.addEventListener("change",()=>J(this,"change",
h,this.fa(m)));e.id&&(m.id=e.id);this.ca(m,e);return m}ea(h){const e=document.createElement("option");e.text=h;return e}fa(h){const e=h.selectedIndex,g=[];for(let q=0,t=h.length;q<t;++q)h.options[q].selected&&g.push(q);return{selectedIndex:e,selectedIndices:g}}ca(h,e){h.title=e.title;h.disabled=!e.isEnabled;h.multiple=!!e.isMultiSelect}Wb(h,e){h.selectedIndex=e}wb(h,e){const g=e.index;e=this.ea(e.text);0>g?h.add(e):h.add(e,g)}Sb(h,e){h.remove(e.index)}Vb(h,e){h.options[e.index].text=e.text}Ab(h){h.innerHTML=
""}Lb(h,e){h.innerHTML="";for(const g of e.items)h.add(this.ea(g));h.selectedIndex=e.selectedIndex;for(const g of e.selectedIndices)if(e=h.options[g])e.selected=!0}})};
