'use strict';function u(g,a,b,d){g.v.mc(g.Xa,a,b,d,void 0)}function B(g,a,b,d){g.v.pa?u(g,a,b,d):g.v.mf()._OnMessageFromDOM({type:"event",component:g.Xa,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function D(g,a,b){g.v.C(g.Xa,a,b)}function F(g,a){for(const [b,d]of a)D(g,b,d)}function G(g){g.Qb||(g.v.Xe(g.ge),g.Qb=!0)}window.ub=class{constructor(g,a){this.v=g;this.Xa=a;this.Qb=!1;this.ge=()=>this.Ea()}hd(){}Ea(){}};function H(g){-1!==g.Pa&&(self.clearTimeout(g.Pa),g.Pa=-1)}
window.Oe=class{constructor(g,a){this.Pc=g;this.Dg=a;this.Pa=-1;this.Rb=-Infinity;this.he=()=>{this.Pa=-1;this.Rb=Date.now();this.bb=!0;this.Pc();this.bb=!1};this.Qd=this.bb=!1}c(){H(this);this.he=this.Pc=null}};"use strict";function K(g,a){const b=a.elementId,d=g.tb(b,a);g.Y.set(b,d);a.isVisible||(d.style.display="none");a=g.wc(d);a.addEventListener("focus",()=>{L(g,"elem-focused",b)});a.addEventListener("blur",()=>{L(g,"elem-blurred",b)});g.Lb&&document.body.appendChild(d)}
function M(g,a,b){D(g,a,d=>{const f=g.Y.get(d.elementId);return b(f,d)})}function L(g,a,b,d){d||(d={});d.elementId=b;u(g,a,d)}function N(g,a,b,d){d||(d={});d.elementId=b;B(g,a,d)}
window.ec=class extends self.ub{constructor(g,a){super(g,a);this.Y=new Map;this.Lb=!0;F(this,[["create",b=>K(this,b)],["destroy",b=>{{b=b.elementId;const d=this.Y.get(b);this.Lb&&d.parentElement.removeChild(d);this.Y.delete(b)}}],["set-visible",b=>{this.Lb&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Lb){var d=this.Y.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=b.height+"px";b=b.fontSize;
null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{{const d=this.Y.get(b.elementId);this.ua(d,b)}}],["focus",b=>this.Kc(b)],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);M(this,"get-element",b=>b)}tb(){throw Error("required override");}ua(){throw Error("required override");}wc(g){return g}Kc(g){const a=this.wc(this.Y.get(g.elementId));
g.focus?a.focus():a.blur()}};"use strict";
{const g=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);function a(e,c){const h=document.createElement("script");h.async=!1;"module"===c&&(h.type="module");if(e.Ng)h.textContent=e.Qg,document.head.appendChild(h);else return new Promise((k,l)=>{h.onload=k;h.onerror=l;h.src=e;document.head.appendChild(h)})}let b=!1,d=!1;function f(){if(!b){try{new Worker("blob://",{get type(){d=!0}})}catch(e){}b=!0}return d}let m=new Audio;const n={"audio/webm; codecs=opus":!!m.canPlayType("audio/webm; codecs=opus"),
"audio/ogg; codecs=opus":!!m.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!m.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!m.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!m.canPlayType("audio/mp4"),"audio/mpeg":!!m.canPlayType("audio/mpeg")};m=null;async function r(e){e=await z(e);return(new TextDecoder("utf-8")).decode(e)}function z(e){return new Promise((c,h)=>{const k=new FileReader;k.onload=l=>c(l.target.result);k.onerror=l=>h(l);k.readAsArrayBuffer(e)})}
const A=[];let v=0;window.RealFile=window.File;const w=[],C=new Map,x=new Map;let I=0;const E=[];self.runOnStartup=function(e){if("function"!==typeof e)throw Error("runOnStartup called without a function");E.push(e)};const J=new Set(["cordova","playable-ad","instant-games"]);window.sa=class e{constructor(c){this.pa=c.Sg;this.na=null;this.F="";this.Zb=c.Pg;this.da=c.ke;this.qb={};this.Ia=this.pb=null;this.Ob=[];this.eb=this.K=this.Na=null;this.Ma=-1;this.Ig=()=>this.Lf();this.La=[];this.B=c.ie;!this.pa||
"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&("module"!==this.da||f())||(this.pa=!1);J.has(this.B)&&this.pa&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this.pa=!1);this.Tb=this.ia=null;"html5"!==this.B&&"playable-ad"!==this.B||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");
this.C("runtime","cordova-fetch-local-file",h=>this.wf(h));this.C("runtime","create-job-worker",()=>this.xf());"cordova"===this.B?document.addEventListener("deviceready",()=>this.Cd(c)):this.Cd(c)}c(){this.sc();this.na&&(this.na=this.na.onmessage=null);this.pb&&(this.pb.terminate(),this.pb=null);this.Ia&&(this.Ia.c(),this.Ia=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}qd(){return g&&"cordova"===this.B}yb(){return g&&J.has(this.B)||navigator.standalone}async Cd(c){if("playable-ad"===
this.B){this.ia=self.c3_base64files;this.Tb={};await this.bf();for(let k=0,l=c.Qa.length;k<l;++k){var h=c.Qa[k].toLowerCase();this.Tb.hasOwnProperty(h)?c.Qa[k]={Ng:!0,Qg:this.Tb[h]}:this.ia.hasOwnProperty(h)&&(c.Qa[k]=URL.createObjectURL(this.ia[h]))}}c.Jg?this.F=c.Jg:(h=location.origin,this.F=("null"===h?"file:///":h)+location.pathname,h=this.F.lastIndexOf("/"),-1!==h&&(this.F=this.F.substr(0,h+1)));c.Ug&&(this.qb=c.Ug);h=new MessageChannel;this.na=h.port1;this.na.onmessage=k=>this._OnMessageFromRuntime(k.data);
window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(k=>this.Hf(k));this.eb=new self.Ke(this);await O(this.eb);this.rd();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.pa?await this.pf(c,h.port2):await this.nf(c,h.port2)}yc(c){c=this.qb.hasOwnProperty(c)?this.qb[c]:c.endsWith("/workermain.js")&&this.qb.hasOwnProperty("workermain.js")?this.qb["workermain.js"]:"playable-ad"===this.B&&this.ia.hasOwnProperty(c.toLowerCase())?
this.ia[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async dc(c,h,k){if(c.startsWith("blob:"))return new Worker(c,k);if(this.qd()&&"file:"===location.protocol)return c=await this.sb(this.Zb+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),k);c=new URL(c,h);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),k)}return new Worker(c,
k)}wa(){return Math.max(window.innerWidth,1)}va(){return Math.max(window.innerHeight,1)}rd(){if(this.yb()){const c=document.documentElement.style,h=document.body.style,k=window.innerWidth<window.innerHeight,l=k?window.screen.width:window.screen.height;h.height=c.height=(k?window.screen.height:window.screen.width)+"px";h.width=c.width=l+"px"}}Ad(c){var h=this.eb;return{baseUrl:this.F,windowInnerWidth:this.wa(),windowInnerHeight:this.va(),devicePixelRatio:window.devicePixelRatio,isFullscreen:e.lc(),
projectData:c.$g,scriptsType:c.ke,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileUrls:window.cr_previewProjectFiles,swClientId:window.Yg||"",exportType:c.ie,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Zg,jobScheduler:{inputPort:h.Vc,outputPort:h.bd,maxNumWorkers:h.Fg},supportedAudioFormats:n,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Zb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.Zb+"opus.wasm.wasm",isiOSCordova:this.qd(),isiOSWebView:this.yb(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async pf(c,h){var k=this.yc(c.Tg);this.pb=await this.dc(k,this.F,{type:this.da,name:"Runtime"});this.K=document.createElement("canvas");this.K.style.display="none";k=this.K.transferControlToOffscreen();document.body.appendChild(this.K);window.c3canvas=this.K;this.pb.postMessage(Object.assign(this.Ad(c),{type:"init-runtime",isInWorker:!0,messagePort:h,canvas:k,workerDependencyScripts:c.gd||
[],engineScripts:c.Qa,projectScripts:c.rb,mainProjectScript:c.je,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[h,k,...P(this.eb)]);this.Ob=w.map(l=>new l(this));this.zd();self.c3_callFunction=(l,p)=>this.Na.qf(l,p);"preview"===this.B&&(self.goToLastErrorScript=()=>this.mc("runtime","go-to-last-error-script"))}async nf(c,h){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Ob=w.map(p=>new p(this));this.zd();var k=
c.Qa.map(p=>"string"===typeof p?(new URL(p,this.F)).toString():p);Array.isArray(c.gd)&&k.unshift(...c.gd);k=await Promise.all(k.map(p=>this.Cc(p,this.da)));await Promise.all(k.map(p=>a(p,this.da)));const l=self.C3_ProjectScriptsStatus;if("module"===this.da){k=c.je;const p=c.rb;for(let [t,q]of p)if(q||(q=t),t===k)try{q=await this.Cc(q,this.da),await a(q,this.da),"preview"!==this.B||l[t]||this.Kd(t,"main script did not run to completion")}catch(y){this.Kd(t,y)}else if("scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))q=
await this.Cc(q,this.da),await a(q,this.da)}else if(c.rb&&0<c.rb.length)try{if(await Promise.all(c.rb.map(p=>a(p[1],this.da))),Object.values(l).some(p=>!p)){self.setTimeout(()=>this.Ld(l),100);return}}catch(p){console.error("[Preview] Error loading project scripts: ",p);self.setTimeout(()=>this.Ld(l),100);return}"preview"===this.B&&"object"!==typeof self.Vg.Wg?(this.Va(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):
(c=Object.assign(this.Ad(c),{isInWorker:!1,messagePort:h,canvas:this.K,runOnStartupFunctions:E}),this.Ed(),this.Ia=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ia,c))}Ld(c){this.Va();c=`Failed to load project script '${Object.entries(c).filter(h=>!h[1]).map(h=>h[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+c);alert(c)}Kd(c,h){this.Va();console.error(`[Preview] Failed to load project main script (${c}): `,h);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ed(){this.Va()}Va(){const c=
window.Kg;c&&(c.parentElement.removeChild(c),window.Kg=null)}async xf(){const c=await Q(this.eb);return{outputPort:c,transferables:[c]}}mf(){if(this.pa)throw Error("not available in worker mode");return this.Ia}mc(c,h,k,l,p){this.na.postMessage({type:"event",component:c,handler:h,dispatchOpts:l||null,data:k,responseId:null},p)}sd(c,h,k,l,p){const t=I++,q=new Promise((y,T)=>{x.set(t,{resolve:y,reject:T})});this.na.postMessage({type:"event",component:c,handler:h,dispatchOpts:l||null,data:k,responseId:t},
p);return q}["_OnMessageFromRuntime"](c){const h=c.type;if("event"===h)return this.Cf(c);if("result"===h)this.Pf(c);else if("runtime-ready"===h)this.Qf();else if("alert-error"===h)this.Va(),alert(c.message);else if("creating-runtime"===h)this.Ed();else throw Error(`unknown message '${h}'`);}Cf(c){const h=c.component,k=c.handler,l=c.data,p=c.responseId;if(c=C.get(h))if(c=c.get(k)){var t=null;try{t=c(l)}catch(q){console.error(`Exception in '${h}' handler '${k}':`,q);null!==p&&this.Gb(p,!1,""+q);return}if(null===
p)return t;t&&t.then?t.then(q=>this.Gb(p,!0,q)).catch(q=>{console.error(`Rejection from '${h}' handler '${k}':`,q);this.Gb(p,!1,""+q)}):this.Gb(p,!0,t)}else console.warn(`[DOM] No handler '${k}' for component '${h}'`);else console.warn(`[DOM] No event handlers for component '${h}'`)}Gb(c,h,k){let l;k&&k.transferables&&(l=k.transferables);this.na.postMessage({type:"result",responseId:c,isOk:h,result:k},l)}Pf(c){const h=c.responseId,k=c.isOk;c=c.result;const l=x.get(h);k?l.resolve(c):l.reject(c);x.delete(h)}C(c,
h,k){let l=C.get(c);l||(l=new Map,C.set(c,l));if(l.has(h))throw Error(`[DOM] Component '${c}' already has handler '${h}'`);l.set(h,k)}static Ba(c){if(w.includes(c))throw Error("DOM handler already added");w.push(c)}zd(){for(const c of this.Ob)if("runtime"===c.Xa){this.Na=c;return}throw Error("cannot find runtime DOM handler");}Hf(c){this.mc("debugger","message",c)}Qf(){for(const c of this.Ob)c.hd()}static lc(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Xe(c){this.La.push(c);
this.Nc()}dg(c){c=this.La.indexOf(c);if(-1===c)throw Error("invalid callback");this.La.splice(c,1);this.La.length||this.sc()}Nc(){-1===this.Ma&&this.La.length&&(this.Ma=requestAnimationFrame(this.Ig))}sc(){-1!==this.Ma&&(cancelAnimationFrame(this.Ma),this.Ma=-1)}Lf(){this.Ma=-1;for(const c of this.La)c();this.Nc()}ta(c){this.Na.ta(c)}Da(c){this.Na.Da(c)}Mc(){this.Na.Mc()}Bb(c){this.Na.Bb(c)}Je(){return!!n["audio/webm; codecs=opus"]}async Bg(c){c=await this.sd("runtime","opus-decode",{arrayBuffer:c},
null,[c]);return new Float32Array(c)}Ie(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}pd(c){return!this.Ie(c)}async Cc(c,h){return"cordova"===this.B&&"module"===h&&(c.startsWith("file:")||"file:"===location.protocol&&this.pd(c))?(c.startsWith(this.F)&&(c=c.substr(this.F.length)),c=await this.sb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async wf(c){const h=c.filename;switch(c.as){case "text":return await this.Be(h);case "buffer":return await this.sb(h);
default:throw Error("unsupported type");}}ld(c){const h=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((k,l)=>{window.resolveLocalFileSystemURL(h,p=>{p.file(k,l)},l)})}async Be(c){c=await this.ld(c);return await r(c)}tc(){if(A.length&&!(8<=v)){v++;var c=A.shift();this.cf(c.filename,c.Rg,c.Mg)}}sb(c){return new Promise((h,k)=>{A.push({filename:c,Rg:l=>{v--;this.tc();h(l)},Mg:l=>{v--;this.tc();k(l)}});this.tc()})}async cf(c,h,k){try{const l=await this.ld(c),p=await z(l);
h(p)}catch(l){k(l)}}async bf(){const c=[];for(const [h,k]of Object.entries(this.ia))c.push(this.af(h,k));await Promise.all(c)}async af(c,h){if("object"===typeof h)this.ia[c]=new Blob([h.str],{type:h.type}),this.Tb[c]=h.str;else{let k=await this.kf(h);k||(k=this.ef(h));this.ia[c]=k}}async kf(c){try{return await (await fetch(c)).blob()}catch(h){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
h),null}}ef(c){c=this.Yf(c);return this.$e(c.data,c.Og)}Yf(c){var h=c.indexOf(",");if(0>h)throw new URIError("expected comma in data: uri");var k=c.substring(h+1);h=c.substring(5,h).split(";");c=h[0]||"";const l=h[2];k="base64"===h[1]||"base64"===l?atob(k):decodeURIComponent(k);return{Og:c,data:k}}$e(c,h){var k=c.length;let l=k>>2,p=new Uint8Array(k),t=new Uint32Array(p.buffer,0,l),q,y;for(y=q=0;q<l;++q)t[q]=c.charCodeAt(y++)|c.charCodeAt(y++)<<8|c.charCodeAt(y++)<<16|c.charCodeAt(y++)<<24;for(k&=
3;k--;)p[y]=c.charCodeAt(y),++y;return new Blob([p],{type:h})}}}"use strict";
{const g=self.sa;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},f={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function n(e){return new Promise((c,h)=>{const k=document.createElement("link");k.onload=()=>c(k);k.onerror=l=>h(l);k.rel=
"stylesheet";k.href=e;document.head.appendChild(k)})}function r(e){return new Promise((c,h)=>{const k=new Image;k.onload=()=>c(k);k.onerror=l=>h(l);k.src=e})}async function z(e){e=URL.createObjectURL(e);try{return await r(e)}finally{URL.revokeObjectURL(e)}}function A(e){return new Promise((c,h)=>{let k=new FileReader;k.onload=l=>c(l.target.result);k.onerror=l=>h(l);k.readAsText(e)})}async function v(e,c,h){if(!/firefox/i.test(navigator.userAgent))return await z(e);var k=await A(e);k=(new DOMParser).parseFromString(k,
"image/svg+xml");const l=k.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const p=l.getAttribute("width"),t=l.getAttribute("height");if(!p.includes("%")&&!t.includes("%"))return await z(e)}l.setAttribute("width",c+"px");l.setAttribute("height",h+"px");k=(new XMLSerializer).serializeToString(k);e=new Blob([k],{type:"image/svg+xml"});return await z(e)}function w(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["canvas",
"body","html"]);function x(e){C.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function I(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await z(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const c=e.getBoundingClientRect();document.body.removeChild(e);return[c.width,c.height]}};self.C3_RasterSvgImageBlob=async function(e,
c,h,k,l){e=await v(e,c,h);const p=document.createElement("canvas");p.width=k;p.height=l;p.getContext("2d").drawImage(e,0,0,c,h);return p};let E=!1;document.addEventListener("pause",()=>E=!0);document.addEventListener("resume",()=>E=!1);function J(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}g.Ba(class extends self.ub{constructor(e){super(e,"runtime");this.Vd=!0;this.Oa=-1;this.dd="any";this.Md=this.Nd=!1;this.Yc=this.mb=this.ya=null;e.C("canvas","update-size",k=>
this.Wf(k));e.C("runtime","invoke-download",k=>this.Gf(k));e.C("runtime","raster-svg-image",k=>this.Mf(k));e.C("runtime","get-svg-image-size",k=>this.Ef(k));e.C("runtime","set-target-orientation",k=>this.Uf(k));e.C("runtime","register-sw",()=>this.Nf());e.C("runtime","post-to-debugger",k=>this.Gd(k));e.C("runtime","go-to-script",k=>this.Gd(k));e.C("runtime","before-start-ticking",()=>this.uf());e.C("runtime","debug-highlight",k=>this.yf(k));e.C("runtime","enable-device-orientation",()=>this.Ze());
e.C("runtime","enable-device-motion",()=>this.Ye());e.C("runtime","add-stylesheet",k=>this.tf(k));e.C("runtime","alert",k=>this.Dc(k));e.C("runtime","hide-cordova-splash",()=>this.Ff());const c=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",k=>{const l=k.target;c.has(l.tagName.toLowerCase())||w(l)||k.preventDefault()});const h=e.K;window.addEventListener("selectstart",x);window.addEventListener("gesturehold",x);h.addEventListener("selectstart",x);h.addEventListener("gesturehold",
x);window.addEventListener("touchstart",x,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",x,{passive:!1}),h.addEventListener("pointerdown",x)):h.addEventListener("touchstart",x);this.jb=0;window.addEventListener("mousedown",k=>{1===k.button&&k.preventDefault()});window.addEventListener("mousewheel",I,{passive:!1});window.addEventListener("wheel",I,{passive:!1});window.addEventListener("resize",()=>this.Xf());e.yb()&&window.addEventListener("focusout",()=>{{const p=
document.activeElement;if(p){var k=p.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));k="textarea"===k?!0:"input"===k?l.has(p.type.toLowerCase()||"text"):w(p)}else k=!1}k||(document.scrollingElement.scrollTop=0)});this.Ja=new Set;this.Ub=new WeakSet;this.ma=!1}uf(){"cordova"===this.v.B?(document.addEventListener("pause",()=>this.Lc(!0)),document.addEventListener("resume",()=>this.Lc(!1))):document.addEventListener("visibilitychange",()=>this.Lc(document.hidden));
return{isSuspended:!(!document.hidden&&!E)}}hd(){window.addEventListener("focus",()=>this.Hb("window-focus"));window.addEventListener("blur",()=>{this.Hb("window-blur",{parentHasFocus:J()});this.jb=0});window.addEventListener("fullscreenchange",()=>this.Fc());window.addEventListener("webkitfullscreenchange",()=>this.Fc());window.addEventListener("mozfullscreenchange",()=>this.Fc());window.addEventListener("fullscreenerror",c=>this.Gc(c));window.addEventListener("webkitfullscreenerror",c=>this.Gc(c));
window.addEventListener("mozfullscreenerror",c=>this.Gc(c));window.addEventListener("keydown",c=>this.Fd("keydown",c));window.addEventListener("keyup",c=>this.Fd("keyup",c));window.addEventListener("dblclick",c=>this.Ic("dblclick",c,d));window.addEventListener("wheel",c=>this.Jf(c));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",c=>{this.zc(c);this.Ua("pointerdown",c)}),this.v.pa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.mb=new self.Oe(()=>this.hf(),
5),this.mb.Qd=!0,window.addEventListener("pointerrawupdate",c=>this.Kf(c))):window.addEventListener("pointermove",c=>this.Ua("pointermove",c)),window.addEventListener("pointerup",c=>this.Ua("pointerup",c)),window.addEventListener("pointercancel",c=>this.Ua("pointercancel",c))):(window.addEventListener("mousedown",c=>{this.zc(c);this.Jc("pointerdown",c)}),window.addEventListener("mousemove",c=>this.Jc("pointermove",c)),window.addEventListener("mouseup",c=>this.Jc("pointerup",c)),window.addEventListener("touchstart",
c=>{this.zc(c);this.Fb("pointerdown",c)}),window.addEventListener("touchmove",c=>this.Fb("pointermove",c)),window.addEventListener("touchend",c=>this.Fb("pointerup",c)),window.addEventListener("touchcancel",c=>this.Fb("pointercancel",c)));const e=()=>this.Mc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}Hb(e,c){u(this,e,c||null,m)}wa(){return this.v.wa()}va(){return this.v.va()}Xf(){const e=
this.wa(),c=this.va();this.Hb("window-resize",{innerWidth:e,innerHeight:c,devicePixelRatio:window.devicePixelRatio});this.v.yb()&&(-1!==this.Oa&&clearTimeout(this.Oa),this.Hd(e,c,0))}eg(e,c,h){-1!==this.Oa&&clearTimeout(this.Oa);this.Oa=setTimeout(()=>this.Hd(e,c,h),48)}Hd(e,c,h){const k=this.wa(),l=this.va();this.Oa=-1;k!=e||l!=c?this.Hb("window-resize",{innerWidth:k,innerHeight:l,devicePixelRatio:window.devicePixelRatio}):10>h&&this.eg(k,l,h+1)}Uf(e){this.dd=e.targetOrientation}xg(){const e=this.dd;
if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(c=>console.warn("[Construct 3] Failed to lock orientation: ",c));else try{let c=!1;screen.lockOrientation?c=screen.lockOrientation(e):screen.webkitLockOrientation?c=screen.webkitLockOrientation(e):screen.mozLockOrientation?c=screen.mozLockOrientation(e):screen.msLockOrientation&&(c=screen.msLockOrientation(e));c||console.warn("[Construct 3] Failed to lock orientation")}catch(c){console.warn("[Construct 3] Failed to lock orientation: ",
c)}}Fc(){const e=g.lc();e&&"any"!==this.dd&&this.xg();u(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.wa(),innerHeight:this.va()})}Gc(e){console.warn("[Construct 3] Fullscreen request failed: ",e);u(this,"fullscreenerror",{isFullscreen:g.lc(),innerWidth:this.wa(),innerHeight:this.va()})}Lc(e){e?this.v.sc():this.v.Nc();u(this,"visibilitychange",{hidden:e})}Fd(e,c){"Backspace"===c.key&&x(c);const h=b.get(c.code)||c.code;B(this,e,{code:h,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,
ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},d)}Jf(e){u(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,timeStamp:e.timeStamp},d)}Ic(e,c,h){a(c)||B(this,e,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,timeStamp:c.timeStamp},h)}Jc(e,c){if(!a(c)){var h=this.jb;"pointerdown"===e&&0!==h?e="pointermove":"pointerup"===
e&&0!==c.buttons&&(e="pointermove");B(this,e,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:h,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},d);this.jb=c.buttons;this.Ic(c.type,c,f)}}Ua(e,c){if(this.mb&&"pointermove"!==e){var h=this.mb;h.bb||(H(h),h.Rb=Date.now())}h=0;"mouse"===c.pointerType&&(h=this.jb);B(this,e,{pointerId:c.pointerId,pointerType:c.pointerType,
button:c.button,buttons:c.buttons,lastButtons:h,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},d);"mouse"===c.pointerType&&(h="mousemove","pointerdown"===e?h="mousedown":"pointerup"===e&&(h="mouseup"),this.Ic(h,c,f),this.jb=c.buttons)}Kf(e){this.Yc=e;e=this.mb;if(-1===e.Pa){var c=Date.now(),h=c-e.Rb,k=e.Dg;
h>=k&&e.Qd?(e.Rb=c,e.bb=!0,e.Pc(),e.bb=!1):e.Pa=self.setTimeout(e.he,Math.max(k-h,4))}}hf(){this.Ua("pointermove",this.Yc);this.Yc=null}Fb(e,c){for(let h=0,k=c.changedTouches.length;h<k;++h){const l=c.changedTouches[h];B(this,e,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:c.timeStamp},d)}}zc(e){window!==window.top&&window.focus();this.Dd(e.target)&&document.activeElement&&!this.Dd(document.activeElement)&&document.activeElement.blur()}Dd(e){return!e||e===document||e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}Ze(){this.Nd||(this.Nd=!0,window.addEventListener("deviceorientation",e=>this.Af(e)),window.addEventListener("deviceorientationabsolute",e=>this.Bf(e)))}Ye(){this.Md||(this.Md=!0,window.addEventListener("devicemotion",
e=>this.zf(e)))}Af(e){u(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},d)}Bf(e){u(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}zf(e){let c=null;var h=e.acceleration;h&&(c={x:h.x||0,y:h.y||0,z:h.z||0});h=null;var k=e.accelerationIncludingGravity;k&&(h={x:k.x||
0,y:k.y||0,z:k.z||0});k=null;const l=e.rotationRate;l&&(k={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});u(this,"devicemotion",{acceleration:c,accelerationIncludingGravity:h,rotationRate:k,interval:e.interval,timeStamp:e.timeStamp},d)}Wf(e){const c=this.v,h=c.K;h.style.width=e.styleWidth+"px";h.style.height=e.styleHeight+"px";h.style.marginLeft=e.marginLeft+"px";h.style.marginTop=e.marginTop+"px";c.rd();this.Vd&&(h.style.display="",this.Vd=!1)}Gf(e){const c=e.url;e=e.filename;const h=document.createElement("a"),
k=document.body;h.textContent=e;h.href=c;h.download=e;k.appendChild(h);h.click();k.removeChild(h)}async Mf(e){var c=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);c=c?await createImageBitmap(e,c):await createImageBitmap(e);return{imageBitmap:c,transferables:[c]}}async Ef(e){return await self.C3_GetSvgImageSize(e.blob)}async tf(e){await n(e.url)}Mc(){var e=[...this.Ja];this.Ja.clear();if(!this.ma)for(const c of e)(e=c.play())&&
e.catch(()=>{this.Ub.has(c)||this.Ja.add(c)})}ta(e){if("function"!==typeof e.play)throw Error("missing play function");this.Ub.delete(e);let c;try{c=e.play()}catch(h){this.Ja.add(e);return}c&&c.catch(()=>{this.Ub.has(e)||this.Ja.add(e)})}Da(e){this.Ja.delete(e);this.Ub.add(e)}Bb(e){this.ma=!!e}Ff(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}yf(e){if(e.show){this.ya||(this.ya=document.createElement("div"),this.ya.id="inspectOutline",document.body.appendChild(this.ya));
var c=this.ya;c.style.display="";c.style.left=e.left-1+"px";c.style.top=e.top-1+"px";c.style.width=e.width+2+"px";c.style.height=e.height+2+"px";c.textContent=e.name}else this.ya&&(this.ya.style.display="none")}Nf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Gd(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}qf(e,c){return this.v.sd(this.Xa,"js-invoke-function",{name:e,params:c},void 0,void 0)}Dc(e){alert(e.message)}})}"use strict";
async function O(g){if(g.Cg)throw Error("already initialised");g.Cg=!0;var a=g.Yb.yc("dispatchworker.js");g.Rc=await g.Yb.dc(a,g.F,{name:"DispatchWorker"});a=new MessageChannel;g.Vc=a.port1;g.Rc.postMessage({type:"_init","in-port":a.port2},[a.port2]);g.bd=await Q(g)}function P(g){return[g.Vc,g.bd]}
async function Q(g){const a=g.Wd.length;var b=g.Yb.yc("jobworker.js");b=await g.Yb.dc(b,g.F,{name:"JobWorker"+a});const d=new MessageChannel,f=new MessageChannel;g.Rc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":f.port2},[d.port2,f.port2]);g.Wd.push(b);return f.port1}
self.Ke=class{constructor(g){this.Yb=g;this.F=g.F;this.F="preview"===g.B?this.F+"c3/workers/":this.F+g.Zb;this.Fg=Math.min(navigator.hardwareConcurrency||2,16);this.Rc=null;this.Wd=[];this.bd=this.Vc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.sa({Sg:!0,Tg:"workermain.js",Qa:["scripts/c3runtime.js"],rb:[],je:"",ke:"module",Pg:"scripts/",gd:[],ie:"html5"}));"use strict";
{function g(b){b.stopPropagation()}function a(b){13!==b.which&&27!==b.which&&b.stopPropagation()}self.sa.Ba(class extends self.ec{constructor(b){super(b,"text-input");M(this,"scroll-to-bottom",d=>this.Rf(d))}tb(b,d){let f;const m=d.type;"textarea"===m?(f=document.createElement("textarea"),f.style.resize="none"):(f=document.createElement("input"),f.type=m);f.style.position="absolute";f.autocomplete="off";f.addEventListener("touchstart",g);f.addEventListener("touchmove",g);f.addEventListener("touchend",
g);f.addEventListener("mousedown",g);f.addEventListener("mouseup",g);f.addEventListener("keydown",a);f.addEventListener("keyup",a);f.addEventListener("click",n=>{n.stopPropagation();N(this,"click",b)});f.addEventListener("dblclick",n=>{n.stopPropagation();N(this,"dblclick",b)});f.addEventListener("input",()=>L(this,"change",b,{text:f.value}));d.id&&(f.id=d.id);this.ua(f,d);return f}ua(b,d){b.value=d.text;b.placeholder=d.placeholder;b.title=d.title;b.disabled=!d.isEnabled;b.readOnly=d.isReadOnly;b.spellcheck=
d.spellCheck;d=d.maxLength;0>d?b.removeAttribute("maxlength"):b.setAttribute("maxlength",d)}Rf(b){b.scrollTop=b.scrollHeight}})}"use strict";
{function g(a){a.stopPropagation()}self.sa.Ba(class extends self.ec{constructor(a){super(a,"button")}tb(a,b){const d=document.createElement("input");var f=d;b.isCheckbox?(d.type="checkbox",f=document.createElement("label"),f.appendChild(d),f.appendChild(document.createTextNode("")),f.style.fontFamily="sans-serif",f.style.userSelect="none",f.style.webkitUserSelect="none",f.style.display="inline-block",f.style.color="black"):d.type="button";f.style.position="absolute";f.addEventListener("touchstart",
g);f.addEventListener("touchmove",g);f.addEventListener("touchend",g);f.addEventListener("mousedown",g);f.addEventListener("mouseup",g);f.addEventListener("keydown",g);f.addEventListener("keyup",g);d.addEventListener("click",()=>N(this,"click",a,{isChecked:d.checked}));b.id&&(d.id=b.id);this.ua(f,b);return f}Bd(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}wc(a){return this.Bd(a)}ua(a,b){const d=this.Bd(a);d.checked=b.isChecked;d.disabled=!b.isEnabled;a.title=b.title;a===d?d.value=b.text:
a.lastChild.textContent=b.text}})}"use strict";
{const g=180/Math.PI;self.ea=class extends self.ub{constructor(a){super(a,"audio");this.Nb=this.f=null;this.Pb=this.Uc=!1;this.oa=()=>this.yg();this.ba=[];this.D=[];this.ha=null;this.Xd="";this.Yd=-1;this.lb=new Map;this.Zc=1;this.ma=!1;this.ed=0;this.ac=1;this.Sc=0;this.$d="HRTF";this.Rd="inverse";this.ae=600;this.Zd=1E4;this.ce=1;this.Td=this.cd=!1;this.fe=this.v.Je();this.ca=new Map;this.Ga=new Set;this.Wc=!1;this.$c="";this.za=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.If(b,d);this.Mb=null;
self.C3Audio_GetOutputStream=()=>this.Df();self.C3Audio_DOMInterface=this;F(this,[["create-audio-context",b=>this.df(b)],["play",b=>this.Zf(b)],["stop",b=>this.vg(b)],["stop-all",()=>this.wg()],["set-paused",b=>this.og(b)],["set-volume",b=>this.tg(b)],["fade-volume",b=>this.jf(b)],["set-master-volume",b=>this.mg(b)],["set-muted",b=>this.ng(b)],["set-silent",b=>this.qg(b)],["set-looping",b=>this.lg(b)],["set-playback-rate",b=>this.pg(b)],["seek",b=>this.fg(b)],["preload",b=>this.$f(b)],["unload",b=>
this.zg(b)],["unload-all",()=>this.Ag()],["set-suspended",b=>this.rg(b)],["add-effect",b=>this.xd(b)],["set-effect-param",b=>this.ig(b)],["remove-effects",b=>this.bg(b)],["tick",b=>this.Vf(b)],["load-state",b=>this.Hc(b)]])}async df(a){a.isiOSCordova&&(this.cd=!0);this.ed=a.timeScaleMode;this.$d=["equalpower","HRTF","soundfield"][a.panningModel];this.Rd=["linear","inverse","exponential"][a.distanceModel];this.ae=a.refDistance;this.Zd=a.maxDistance;this.ce=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.fe||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.yd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.yd()};this.Nb=this.f.createGain();this.Nb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.fc();try{await Promise.all(a.preloadList.map(d=>this.Db(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}yd(){this.Pb||(this.Uc=!1,window.addEventListener("pointerup",this.oa,!0),window.addEventListener("touchend",this.oa,!0),window.addEventListener("click",this.oa,!0),window.addEventListener("keydown",this.oa,!0),this.Pb=!0)}ff(){this.Pb&&(this.Uc=!0,window.removeEventListener("pointerup",this.oa,!0),window.removeEventListener("touchend",
this.oa,!0),window.removeEventListener("click",this.oa,!0),window.removeEventListener("keydown",this.oa,!0),this.Pb=!1)}yg(){if(!this.Uc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.ff()}}W(){return this.f}fc(){return this.f.currentTime}qa(){return this.Nb}nd(a){return(a=this.ca.get(a.toLowerCase()))?a[0].P():this.qa()}le(a,b){a=a.toLowerCase();let d=this.ca.get(a);
d||(d=[],this.ca.set(a,d));b.kg(d.length);b.sg(a);d.push(b);this.Jd(a)}Jd(a){let b=this.qa();const d=this.ca.get(a);if(d&&d.length){b=d[0].P();for(let f=0,m=d.length;f<m;++f){const n=d[f];f+1===m?n.S(this.qa()):n.S(d[f+1].P())}}for(const f of this.ka(a))f.Pe(b);this.za&&this.$c===a&&(this.za.disconnect(),this.za.connect(b))}wb(){return this.Zc}xb(){return this.ma}jg(){this.Td=!0}De(a,b){return b?this.v.Bg(a).then(d=>{const f=this.f.createBuffer(1,d.length,48E3);f.getChannelData(0).set(d);return f}):
new Promise((d,f)=>{this.f.decodeAudioData(a,d,f)})}ta(a){this.v.ta(a)}Da(a){this.v.Da(a)}td(a){let b=0;for(let d=0,f=this.D.length;d<f;++d){const m=this.D[d];this.D[b]=m;m.L===a?m.c():++b}this.D.length=b}Qe(){let a=0;for(let b=0,d=this.ba.length;b<d;++b){const f=this.ba[b];this.ba[a]=f;f.ra()?f.c():++a}this.ba.length=a}*ka(a){if(a)for(const b of this.D)self.ea.Ee(b.$,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Db(a,b,d,f,m){for(const n of this.ba)if(n.Sa()===b)return await R(n),
n;if(m)return null;f&&(this.cd||this.Td)&&this.Qe();m="audio/webm; codecs=opus"===d&&!this.fe;f&&m&&this.jg();a=!f||this.cd||m?new self.ze(this,a,b,d,f,m):new self.xe(this,a,b,d,f);this.ba.push(a);await R(a);return a}async vc(a,b,d,f,m){for(const n of this.D)if(n.Sa()===b&&(n.cc()||m))return n.Se(f),n;a=await this.Db(a,b,d,m);f="html5"===a.Oc?new self.ye(a.i,a,f):new self.Ae(a.i,a,f);this.D.push(f);return f}We(a){let b=this.lb.get(a);if(!b){let d=null;b={fd:0,promise:new Promise(f=>d=f),resolve:d};
this.lb.set(a,b)}b.fd++}cg(a){const b=this.lb.get(a);if(!b)throw Error("expected pending tag");b.fd--;0===b.fd&&(b.resolve(),this.lb.delete(a))}rc(a){a||(a=this.Xd);return(a=this.lb.get(a))?a.promise:Promise.resolve()}Eb(){if(0<this.Ga.size)G(this);else for(const a of this.D)if(a.od()){G(this);break}}Ea(){for(var a of this.Ga)a.Ea();a=this.fc();for(var b of this.D)b.Ea(a);b=this.D.filter(d=>d.od()).map(d=>d.Ra());u(this,"state",{tickCount:this.Yd,audioInstances:b,analysers:[...this.Ga].map(d=>d.Ge())});
0===b.length&&0===this.Ga.size&&this.Qb&&(this.v.dg(this.ge),this.Qb=!1)}nc(a,b,d){u(this,"trigger",{type:a,tag:b,aiid:d})}async Zf(a){const b=a.originalUrl,d=a.url,f=a.type,m=a.isMusic,n=a.tag,r=a.isLooping,z=a.vol,A=a.pos,v=a.panning;let w=a.off;0<w&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),w=w-a.performanceTime/1E3+a.contextTime):w=w-performance.now()/1E3+this.f.currentTime);this.Xd=n;this.We(n);try{this.ha=await this.vc(b,d,f,n,m),v?(this.ha.Ab(!0),this.ha.Re(v.x,
v.y,v.angle,v.innerAngle,v.outerAngle,v.outerGain),v.hasOwnProperty("uid")&&this.ha.Te(v.uid)):this.ha.Ab(!1),this.ha.Play(r,z,A,w)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.cg(n)}G(this)}vg(a){a=a.tag;for(const b of this.ka(a))b.la()}wg(){for(const a of this.D)a.la()}og(a){const b=a.tag;a=a.paused;for(const d of this.ka(b))a?d.Ta():d.zb();this.Eb()}tg(a){const b=a.tag;a=a.vol;for(const d of this.ka(b))d.Cb(a)}async jf(a){const b=a.tag,d=a.vol,
f=a.duration;a=a.stopOnEnd;await this.rc(b);for(const m of this.ka(b))m.Fe(d,f,a);this.Eb()}mg(a){this.Zc=a.vol;for(const b of this.D)b.Jb()}ng(a){const b=a.tag;a=a.isMuted;for(const d of this.ka(b))d.ud(a)}qg(a){this.ma=a.isSilent;this.v.Bb(this.ma);for(const b of this.D)b.Ib()}lg(a){const b=a.tag;a=a.isLooping;for(const d of this.ka(b))d.pc(a)}async pg(a){const b=a.tag;a=a.rate;await this.rc(b);for(const d of this.ka(b))d.wd(a)}async fg(a){const b=a.tag;a=a.pos;await this.rc(b);for(const d of this.ka(b))d.oc(a)}async $f(a){const b=
a.originalUrl,d=a.url,f=a.type;a=a.isMusic;try{await this.vc(b,d,f,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async zg(a){if(a=await this.Db("",a.url,a.type,a.isMusic,!0))a.c(),a=this.ba.indexOf(a),-1!==a&&this.ba.splice(a,1)}Ag(){for(const a of this.ba)a.c();this.ba.length=0}rg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.qc(a);a&&this.f.suspend&&this.f.suspend()}Vf(a){this.ac=a.timeScale;this.Sc=a.gameTime;this.Yd=a.tickCount;if(0!==
this.ed)for(var b of this.D)b.Fa();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const f of this.D)f.ga===a&&f.vd(d.x,d.y,d.angle)}}async xd(a){var b=a.type;const d=a.tag;var f=a.params;if("filter"===b)f=new self.re(this,...f);else if("delay"===b)f=new self.pe(this,...f);else if("convolution"===b){b=null;try{b=await this.Db(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",
m);return}f=new self.oe(this,b.aa,...f);f.gg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)f=new self.se(this,...f);else if("phaser"===b)f=new self.ue(this,...f);else if("gain"===b)f=new self.te(this,...f);else if("tremolo"===b)f=new self.we(this,...f);else if("ringmod"===b)f=new self.ve(this,...f);else if("distortion"===b)f=new self.qe(this,...f);else if("compressor"===b)f=new self.ne(this,...f);else if("analyser"===b)f=new self.me(this,...f);else throw Error("invalid effect type");this.le(d,
f);this.Id()}ig(a){const b=a.index,d=a.param,f=a.value,m=a.ramp,n=a.time;a=this.ca.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,f,m,n),this.Id())}bg(a){a=a.tag.toLowerCase();const b=this.ca.get(a);if(b&&b.length){for(const d of b)d.c();this.ca.delete(a);this.Jd(a)}}Ve(a){this.Ga.add(a);this.Eb()}ag(a){this.Ga.delete(a)}Id(){this.Wc||(this.Wc=!0,Promise.resolve().then(()=>this.gf()))}gf(){const a={};for(const [b,d]of this.ca)a[b]=d.map(f=>f.Ra());u(this,"fxstate",{fxstate:a});this.Wc=!1}async Hc(a){const b=
a.saveLoadMode;if(3!==b)for(var d of this.D)d.ra()&&1===b||(d.ra()||2!==b)&&d.la();for(const f of this.ca.values())for(const m of f)m.c();this.ca.clear();this.ac=a.timeScale;this.Sc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.ma=a.isSilent;this.v.Bb(this.ma);this.Zc=a.masterVolume;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(m=>this.xd(m))));await Promise.all(d);await Promise.all(a.playing.map(f=>this.rf(f,b)));this.Eb()}async rf(a,b){if(3!==
b){var d=a.bufferOriginalUrl,f=a.bufferUrl,m=a.bufferType,n=a.isMusic,r=a.tag,z=a.isLooping,A=a.volume,v=a.playbackTime;if(!n||1!==b)if(n||2!==b){b=null;try{b=await this.vc(d,f,m,r,n)}catch(w){console.error("[Construct 3] Audio: error loading audio state: ",w);return}b.Ne(a.pan);b.Play(z,A,v,0);a.isPlaying||b.Ta();b.Bc(a)}}}If(a,b){this.za&&this.za.disconnect();this.$c=b.toLowerCase();this.za=this.f.createMediaStreamSource(a);this.za.connect(this.nd(this.$c))}Df(){this.Mb||(this.Mb=this.f.createMediaStreamDestination(),
this.Nb.connect(this.Mb));return this.Mb.stream}static Ee(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Ue(a){return a*g}static Ce(a){return Math.pow(10,a/20)}static md(a){return Math.max(Math.min(self.ea.Ce(a),1),0)}static Me(a){return Math.log(a)/Math.log(10)*20}static Le(a){return self.ea.Me(Math.max(Math.min(a,1),0))}static Lg(a,b){return 1-Math.exp(-b*a)}};self.sa.Ba(self.ea)}"use strict";function R(g){g.Sb||(g.Sb=g.Ac());return g.Sb}
self.jd=class{constructor(g,a,b,d,f){this.i=g;this.Hg=a;this.Aa=b;this.R=d;this.Eg=f;this.Oc="";this.Sb=null}c(){this.Sb=this.i=null}Ac(){}W(){return this.i.W()}ic(){return this.Hg}Sa(){return this.Aa}hc(){return this.R}ra(){return this.Eg}fa(){}};"use strict";
self.xe=class extends self.jd{constructor(g,a,b,d,f){super(g,a,b,d,f);this.Oc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.fb=this.gb=null;this.J.addEventListener("canplaythrough",()=>!0);this.kb=this.W().createGain();this.ib=null;this.J.addEventListener("canplay",()=>{this.gb&&(this.gb(),this.fb=this.gb=null);!this.ib&&this.J&&(this.ib=this.W().createMediaElementSource(this.J),this.ib.connect(this.kb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.Aa}' error: `,m);this.fb&&(this.fb(m),this.fb=this.gb=null)})}c(){this.i.td(this);this.kb.disconnect();this.kb=null;this.ib.disconnect();this.ib=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}Ac(){return new Promise((g,a)=>{this.gb=g;this.fb=a;this.J.src=this.Aa})}O(){return this.J}fa(){return this.J.duration}};"use strict";
async function S(g){if(g.xa)return g.xa;var a=g.i.v;if("cordova"===a.B&&a.pd(g.Aa)&&"file:"===location.protocol)g.xa=await a.sb(g.Aa);else{a=await fetch(g.Aa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);g.xa=await a.arrayBuffer()}}async function U(g){if(g.aa)return g.aa;g.aa=await g.i.De(g.xa,g.Gg);g.xa=null}
self.ze=class extends self.jd{constructor(g,a,b,d,f,m){super(g,a,b,d,f);this.Oc="webaudio";this.aa=this.xa=null;this.Gg=!!m}c(){this.i.td(this);this.aa=this.xa=null;super.c()}async Ac(){try{await S(this),await U(this)}catch(g){console.error(`[Construct 3] Failed to load audio '${this.Aa}': `,g)}}fa(){return this.aa?this.aa.duration:0}};"use strict";
{let g=0;self.kd=class{constructor(a,b,d){this.i=a;this.L=b;this.$=d;this.Kb=g++;this.M=this.W().createGain();this.M.connect(this.qa());this.A=null;this.cb=!1;this.H=!0;this.V=this.ja=this.G=!1;this.ob=1;this.Ha=!1;this.Z=1;a=this.i.ed;this.Xc=1===a&&!this.ra()||2===a;this.$a=this.ga=-1;this.ee=!1}c(){this.L=this.i=null;this.A&&(this.A.disconnect(),this.A=null);this.M.disconnect();this.M=null}W(){return this.i.W()}qa(){return this.i.nd(this.$)}wb(){return this.i.wb()}vb(){return this.Xc?this.i.Sc:
performance.now()/1E3}ic(){return this.L.ic()}Sa(){return this.L.Sa()}hc(){return this.L.hc()}ra(){return this.L.ra()}Se(a){this.$=a}T(){}cc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}od(){return!this.H&&!this.T()}Ca(){}fa(){return this.L.fa()}Play(){}la(){}Ta(){}zb(){}Cb(a){this.ob=a;this.M.gain.cancelScheduledValues(0);this.$a=-1;this.M.gain.value=this.jc()}Fe(a,b,d){if(!this.Ha){a*=this.wb();var f=this.M.gain;f.cancelScheduledValues(0);var m=this.i.fc();b=m+b;f.setValueAtTime(f.value,m);
f.linearRampToValueAtTime(a,b);this.ob=a;this.$a=b;this.ee=d}}Jb(){this.Cb(this.ob)}Ea(a){-1!==this.$a&&a>=this.$a&&(this.$a=-1,this.ee&&this.la(),this.i.nc("fade-ended",this.$,this.Kb))}jc(){const a=this.ob*this.wb();return isFinite(a)?a:0}ud(a){a=!!a;this.Ha!==a&&(this.Ha=a,this.Ib())}xb(){return this.i.xb()}Ib(){}pc(){}wd(a){this.Z!==a&&(this.Z=a,this.Fa())}Fa(){}oc(){}qc(){}Ab(a){a=!!a;this.cb!==a&&((this.cb=a)?(this.A||(this.A=this.W().createPanner(),this.A.panningModel=this.i.$d,this.A.distanceModel=
this.i.Rd,this.A.refDistance=this.i.ae,this.A.maxDistance=this.i.Zd,this.A.rolloffFactor=this.i.ce),this.M.disconnect(),this.M.connect(this.A),this.A.connect(this.qa())):(this.A.disconnect(),this.M.disconnect(),this.M.connect(this.qa())))}Re(a,b,d,f,m,n){this.cb&&(this.vd(a,b,d),a=self.ea.Ue,this.A.coneInnerAngle=a(f),this.A.coneOuterAngle=a(m),this.A.coneOuterGain=n)}vd(a,b,d){this.cb&&(this.A.setPosition(a,b,0),this.A.setOrientation(Math.cos(d),Math.sin(d),0))}Te(a){this.ga=a}kc(){}Pe(a){const b=
this.A||this.M;b.disconnect();b.connect(a)}Ra(){return{aiid:this.Kb,tag:this.$,duration:this.fa(),volume:this.ob,isPlaying:this.IsPlaying(),playbackTime:this.Ca(),playbackRate:this.Z,uid:this.ga,bufferOriginalUrl:this.ic(),bufferUrl:"",bufferType:this.hc(),isMusic:this.ra(),isLooping:this.V,isMuted:this.Ha,resumePosition:this.kc(),pan:this.He()}}Bc(a){this.wd(a.playbackRate);this.ud(a.isMuted)}He(){if(!this.A)return null;const a=this.A;return{pos:[a.positionX.value,a.positionY.value,a.positionZ.value],
orient:[a.orientationX.value,a.orientationY.value,a.orientationZ.value],cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}Ne(a){a?(this.Ab(!0),a=this.A,a.setPosition(...a.pos),a.setOrientation(...a.orient),a.coneInnerAngle=a.cia,a.coneOuterAngle=a.coa,a.coneOuterGain=a.cog,this.ga=a.uid):this.Ab(!1)}}}"use strict";
self.ye=class extends self.kd{constructor(g,a,b){super(g,a,b);this.L.kb.connect(this.M);this.L.onended=()=>this.Ec()}c(){this.la();this.L.kb.disconnect();super.c()}O(){return this.L.O()}Ec(){this.H=!0;this.ga=-1;this.i.nc("ended",this.$,this.Kb)}T(){return this.O().ended}cc(){return this.H?!0:this.T()}Ca(g){let a=this.O().currentTime;g&&(a*=this.Z);this.V||(a=Math.min(a,this.fa()));return a}Play(g,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==g&&(d.loop=g);this.Cb(a);d.muted&&
(d.muted=!1);if(d.currentTime!==b)try{d.currentTime=b}catch(f){console.warn(`[Construct 3] Exception seeking audio '${this.L.Sa()}' to position '${b}': `,f)}this.i.ta(d);this.G=this.H=!1;this.V=g;this.Z=1}la(){const g=this.O();g.paused||g.pause();this.i.Da(g);this.H=!0;this.G=!1;this.ga=-1}Ta(){if(!(this.G||this.H||this.T())){var g=this.O();g.paused||g.pause();this.i.Da(g);this.G=!0}}zb(){!this.G||this.H||this.T()||(this.i.ta(this.O()),this.G=!1)}Ib(){this.O().muted=this.Ha||this.xb()}pc(g){g=!!g;
this.V!==g&&(this.V=g,this.O().loop=g)}Fa(){let g=this.Z;this.Xc&&(g*=this.i.ac);try{this.O().playbackRate=g}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${g}':`,a)}}oc(g){if(!this.H&&!this.T())try{this.O().currentTime=g}catch(a){console.warn(`[Construct 3] Error seeking audio to '${g}': `,a)}}kc(){return this.Ca()}qc(g){g?this.IsPlaying()?(this.O().pause(),this.ja=!0):this.ja=!1:this.ja&&(this.i.ta(this.O()),this.ja=!1)}};"use strict";
function V(g){g.j&&g.j.disconnect();g.j=null;g.Wa=null}
self.Ae=class extends self.kd{constructor(g,a,b){super(g,a,b);this.j=null;this.Vb=d=>this.Ec(d);this.Tc=!0;this.Wa=null;this.N=this.$b=0;this.ad=1}c(){this.la();V(this);this.Vb=null;super.c()}Ec(g){this.G||this.ja||g.target!==this.Wa||(this.H=this.Tc=!0,this.ga=-1,V(this),this.i.nc("ended",this.$,this.Kb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Tc}cc(){return!this.j||this.H?!0:this.T()}Ca(g){let a;a=this.G?this.N:this.vb()-this.$b;g&&(a*=this.Z);this.V||(a=Math.min(a,this.fa()));return a}Play(g,
a,b,d){this.ad=1;this.Cb(a);V(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.aa;this.j.connect(this.M);this.Wa=this.j;this.j.onended=this.Vb;this.j.loop=g;this.j.start(d,b);this.G=this.H=this.Tc=!1;this.V=g;this.Z=1;this.$b=this.vb()-b}la(){if(this.j)try{this.j.stop(0)}catch(g){}this.H=!0;this.G=!1;this.ga=-1}Ta(){this.G||this.H||this.T()||(this.N=this.Ca(!0),this.V&&(this.N%=this.fa()),this.G=!0,this.j.stop(0))}zb(){!this.G||this.H||this.T()||(V(this),this.j=this.W().createBufferSource(),
this.j.buffer=this.L.aa,this.j.connect(this.M),this.Wa=this.j,this.j.onended=this.Vb,this.j.loop=this.V,this.Jb(),this.Fa(),this.$b=this.vb()-this.N/(this.Z||.001),this.j.start(0,this.N),this.G=!1)}jc(){return super.jc()*this.ad}Ib(){this.ad=this.Ha||this.xb()?0:1;this.Jb()}pc(g){g=!!g;this.V!==g&&(this.V=g,this.j&&(this.j.loop=g))}Fa(){let g=this.Z;this.Xc&&(g*=this.i.ac);this.j&&(this.j.playbackRate.value=g)}oc(g){this.H||this.T()||(this.G?this.N=g:(this.Ta(),this.N=g,this.zb()))}kc(){return this.N}qc(g){g?
this.IsPlaying()?(this.ja=!0,this.N=this.Ca(!0),this.V&&(this.N%=this.fa()),this.j.stop(0)):this.ja=!1:this.ja&&(V(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.aa,this.j.connect(this.M),this.Wa=this.j,this.j.onended=this.Vb,this.j.loop=this.V,this.Jb(),this.Fa(),this.$b=this.vb()-this.N/(this.Z||.001),this.j.start(0,this.N),this.ja=!1)}Bc(g){super.Bc(g);this.N=g.resumePosition}};"use strict";
{class g{constructor(a){this.i=a;this.f=a.W();this.Ud=-1;this.R=this.$="";this.g=null}c(){this.f=null}kg(a){this.Ud=a}sg(a){this.$=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,d,f){a.cancelScheduledValues(0);if(0===f)a.value=b;else{var m=this.f.currentTime;f+=m;switch(d){case 0:a.setValueAtTime(b,f);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,f);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,f)}}}Ra(){return{type:this.R,tag:this.$,params:this.g}}}
self.re=class extends g{constructor(a,b,d,f,m,n,r){super(a);this.R="filter";this.g=[b,d,f,m,n,r];this.l=this.o();this.b=this.o();this.b.gain.value=r;this.a=this.o();this.a.gain.value=1-r;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=d;this.u.detune.value=f;this.u.Q.value=m;this.u.gain.vlaue=n;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,f);this.m(this.a.gain,1-b,d,f);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,d,f);break;case 2:this.g[2]=b;this.m(this.u.detune,b,d,f);break;case 3:this.g[3]=b;this.m(this.u.Q,b,d,f);break;case 4:this.g[4]=b,this.m(this.u.gain,b,d,f)}}};self.pe=class extends g{constructor(a,b,d,f){super(a);this.R="delay";this.g=[b,d,f];this.l=
this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=1-f;this.hb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.Za=this.o();this.Za.gain.value=d;this.l.connect(this.hb);this.l.connect(this.a);this.hb.connect(this.b);this.hb.connect(this.U);this.U.connect(this.Za);this.Za.connect(this.hb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.hb.disconnect();this.U.disconnect();this.Za.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){const m=self.ea.md;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,f);this.m(this.a.gain,1-b,d,f);break;case 4:this.g[1]=m(b);this.m(this.Za.gain,m(b),d,f);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,f)}}};self.oe=class extends g{constructor(a,b,d,f){super(a);this.R="convolution";this.g=[d,f];this.Pd=this.Od="";this.l=this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=
1-f;this.Ya=this.f.createConvolver();this.Ya.normalize=d;this.Ya.buffer=b;this.l.connect(this.Ya);this.l.connect(this.a);this.Ya.connect(this.b)}c(){this.l.disconnect();this.Ya.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,f),this.m(this.a.gain,1-b,d,f)}}gg(a,b){this.Od=a;this.Pd=b}Ra(){const a=
super.Ra();a.bufferOriginalUrl=this.Od;a.bufferUrl="";a.bufferType=this.Pd;return a}};self.se=class extends g{constructor(a,b,d,f,m,n){super(a);this.R="flanger";this.g=[b,d,f,m,n];this.l=this.o();this.a=this.o();this.a.gain.value=1-n/2;this.b=this.o();this.b.gain.value=n/2;this.ab=this.o();this.ab.gain.value=m;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=f;this.I=this.o();this.I.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.ab);this.ab.connect(this.U);this.s.connect(this.I);this.I.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.ab.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,f);this.m(this.a.gain,1-b/2,d,f);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,d,f);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,d,f);break;case 8:this.g[3]=b/100,this.m(this.ab.gain,b/100,d,f)}}};self.ue=class extends g{constructor(a,b,d,f,m,n,r){super(a);this.R="phaser";this.g=[b,d,f,m,n,r];this.l=this.o();this.a=this.o();this.a.gain.value=1-r/2;this.b=this.o();this.b.gain.value=r/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
d;this.u.Q.value=f;this.s=this.f.createOscillator();this.s.frequency.value=n;this.I=this.o();this.I.gain.value=m;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.I);this.I.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,f);this.m(this.a.gain,1-b/2,d,f);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,d,f);break;case 2:this.g[1]=b;this.m(this.u.detune,b,d,f);break;case 3:this.g[2]=b;this.m(this.u.Q,b,d,f);break;case 6:this.g[3]=b;this.m(this.I.gain,b,d,f);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,d,f)}}};self.te=class extends g{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,f){const m=self.ea.md;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),d,f)}}};self.we=class extends g{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.I=this.o();this.I.gain.value=d/2;this.s.connect(this.I);this.I.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,f);this.m(this.I.gain,b/2,d,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,f)}}};self.ve=class extends g{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.nb=this.o();this.nb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.nb.gain);this.s.start(0);this.l.connect(this.nb);this.l.connect(this.a);this.nb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.nb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,f);
this.m(this.a.gain,1-b,d,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,f)}}};self.qe=class extends g{constructor(a,b,d,f,m,n){super(a);this.R="distortion";this.g=[b,d,f,m,n];this.l=this.o();this.Xb=this.o();this.Wb=this.o();this.hg(f,m);this.b=this.o();this.b.gain.value=n;this.a=this.o();this.a.gain.value=1-n;this.bc=this.f.createWaveShaper();this.Qc=new Float32Array(65536);this.lf(b,d);this.bc.curve=this.Qc;this.l.connect(this.Xb);this.l.connect(this.a);this.Xb.connect(this.bc);this.bc.connect(this.Wb);
this.Wb.connect(this.b)}c(){this.l.disconnect();this.Xb.disconnect();this.bc.disconnect();this.Wb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}hg(a,b){.01>a&&(a=.01);this.Xb.gain.value=a;this.Wb.gain.value=Math.pow(1/a,.6)*b}lf(a,b){for(let d=0;32768>d;++d){let f=d/32768;f=this.ug(f,a,b);this.Qc[32768+d]=f;this.Qc[32768-d-1]=-f}}ug(a,b,d){d=1.05*d*b-b;const f=0>a?-a:a;return(f<b?f:b+d*self.ea.Lg(f-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,f),this.m(this.a.gain,1-b,d,f)}}};self.ne=class extends g{constructor(a,b,d,f,m,n){super(a);this.R="compressor";this.g=[b,d,f,m,n];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=f;this.h.attack.value=m;this.h.release.value=n}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.me=class extends g{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Sd=new Float32Array(this.h.frequencyBinCount);this.de=new Uint8Array(b);this.be=this.Ka=0;this.i.Ve(this)}c(){this.i.ag(this);this.h.disconnect();super.c()}Ea(){this.h.getFloatFrequencyData(this.Sd);this.h.getByteTimeDomainData(this.de);const a=this.h.fftSize;let b=this.Ka=0;for(var d=0;d<a;++d){let f=(this.de[d]-128)/128;0>f&&(f=-f);
this.Ka<f&&(this.Ka=f);b+=f*f}d=self.ea.Le;this.Ka=d(this.Ka);this.be=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Ge(){return{tag:this.$,index:this.Ud,peak:this.Ka,rms:this.be,binCount:this.h.frequencyBinCount,freqBins:this.Sd}}}}"use strict";
{function g(a){a.stopPropagation()}self.sa.Ba(class extends self.ec{constructor(a){super(a,"list");M(this,"set-selected-index",(b,d)=>this.Tf(b,d.selectedIndex));M(this,"add-item",(b,d)=>this.sf(b,d));M(this,"remove-item",(b,d)=>this.Of(b,d));M(this,"set-item",(b,d)=>this.Sf(b,d));M(this,"clear",b=>this.vf(b));M(this,"load-state",(b,d)=>this.Hc(b,d))}tb(a,b){const d=b.isDropdown,f=b.isMultiSelect,m=b.items,n=document.createElement("select");n.style.position="absolute";n.style.userSelect="none";n.style.webkitUserSelect=
"none";n.multiple=f;d||(n.size=2);for(const r of m)n.add(this.uc(r));n.addEventListener("touchstart",g);n.addEventListener("touchmove",g);n.addEventListener("touchend",g);n.addEventListener("mousedown",g);n.addEventListener("mouseup",g);n.addEventListener("click",r=>{r.stopPropagation();N(this,"click",a,this.xc(n))});n.addEventListener("dblclick",r=>{r.stopPropagation();N(this,"dblclick",a,this.xc(n))});n.addEventListener("change",()=>L(this,"change",a,this.xc(n)));b.id&&(n.id=b.id);this.ua(n,b);
return n}uc(a){const b=document.createElement("option");b.text=a;return b}xc(a){const b=a.selectedIndex,d=[];for(let f=0,m=a.length;f<m;++f)a.options[f].selected&&d.push(f);return{selectedIndex:b,selectedIndices:d}}ua(a,b){a.title=b.title;a.disabled=!b.isEnabled;a.multiple=!!b.isMultiSelect}Tf(a,b){a.selectedIndex=b}sf(a,b){const d=b.index;b=this.uc(b.text);0>d?a.add(b):a.add(b,d)}Of(a,b){a.remove(b.index)}Sf(a,b){a.options[b.index].text=b.text}vf(a){a.innerHTML=""}Hc(a,b){a.innerHTML="";for(const d of b.items)a.add(this.uc(d));
a.selectedIndex=b.selectedIndex;for(const d of b.selectedIndices)if(b=a.options[d])b.selected=!0}})}"use strict";function W(g){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>u(g,"sw-message",a.data))}
function X(g){g=g.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(g).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(g):screen.webkitLockOrientation?a=screen.webkitLockOrientation(g):screen.mozLockOrientation?a=screen.mozLockOrientation(g):screen.msLockOrientation&&(a=screen.msLockOrientation(g));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.sa.Ba(class extends self.ub{constructor(g){super(g,"browser");this.B="";F(this,[["get-initial-state",a=>{this.B=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>W(this)],
["alert",a=>this.Dc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Kc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>X(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===b)window.forward();else if("home"===b)window.home();else if("reload"===b)location.reload();else if("url"===b){b=a.url;var d=a.target;a=a.exportType;"windows-uwp"===a&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a?window.open(b,"_blank"):this.Xg||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,d=a.tag,"windows-uwp"===a.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,d))}],["request-fullscreen",
a=>{{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{document.exitFullscreen?document.exitFullscreen():
document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{u(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{u(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{u(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",
()=>{u(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",a=>{a.handled=!0;u(this,"backbutton")})}Dc(g){alert(g.message)}Kc(g){g=g.isFocus;if("nwjs"===this.B){const a="nwjs"===this.B?nw.Window.get():null;g?a.focus():a.blur()}else g?window.focus():window.blur()}});
